on: [push]
jobs:
    job0:
        name: do a thing, in a container
        steps:
            - name: step
              uses: jepler/circuitpython-actions-build@HEAD
              with:
                run: uname -a
